Update mutter

diff --git a/mutter-dynamic-buffering/PKGBUILD b/mutter-dynamic-buffering/PKGBUILD
--- a/mutter-dynamic-buffering/PKGBUILD
+++ b/mutter-dynamic-buffering/PKGBUILD
@@ -1,33 +1,69 @@
 # Maintainer: Dennis ten Hoove <contact@arkanelinux.org>
-
-pkgbase=mutter-dynamic-buffering
-pkgname=mutter-dynamic-buffering
-pkgver=45.5
+pkgname='mutter'
+_pkgname='mutter-dynamic-buffering'
+replaces=('mutter-dynamic-buffering')
+pkgver=46.0
 pkgrel=1
 pkgdesc="Window manager and compositor for GNOME (with dynamic triple/double buffering)"
 url="https://gitlab.gnome.org/GNOME/mutter"
 arch=(x86_64)
-license=(GPL)
+license=(GPL-2.0-or-later)
 depends=(
+	libgirepository
+  at-spi2-core
+  cairo
   colord
   dconf
+  fontconfig
+  fribidi
+  gcc-libs
+  gdk-pixbuf2
+  glib2
+  glibc
   gnome-desktop-4
   gnome-settings-daemon
   graphene
   gsettings-desktop-schemas
+  gtk4
+  harfbuzz
   iio-sensor-proxy
   lcms2
   libcanberra
+  libcolord
   libdisplay-info
+  libdrm
   libei
+  libglvnd
   libgudev
+  libice
   libinput
+  libpipewire
   libsm
   libsysprof-capture
+  libwacom
+  libx11
+  libxau
+  libxcb
+  libxcomposite
+  libxcursor
+  libxdamage
+  libxext
+  libxfixes
+  libxi
+  libxinerama
+  libxkbcommon
   libxkbcommon-x11
   libxkbfile
+  libxrandr
+  libxtst
+  mesa
+  pango
   pipewire
+  pixman
+  python
   startup-notification
+  systemd-libs
+  wayland
   xorg-xwayland
 )
 makedepends=(
@@ -41,6 +77,7 @@ makedepends=(
   wayland-protocols
   xorg-server
   xorg-server-xvfb
+	cmake
 )
 _checkdepends=(
   gnome-session
@@ -48,23 +85,23 @@ _checkdepends=(
   wireplumber
   zenity
 )
-_commit=4e8ccf5f9c177595aac11895ed50a4e35d5087e4  # tags/45.5^0
+_commit=c4753689e3413cd9332d885dd0297b3b7d9ba9ca  # tags/46.0^0
 source=(
-  "$pkgname::git+https://gitlab.gnome.org/GNOME/mutter.git#commit=$_commit"
+  "$_pkgname::git+https://gitlab.gnome.org/GNOME/mutter.git#commit=$_commit"
   'mr1441.patch'
 )
 sha256sums=(
   'SKIP'
-  '5b0e927eb2873256c7999ebc711f5f0db2296550d7dbe51e757335e2b77d016c'
+  '0146f9e566786164a0d59d4dbbd87a8a97c29af0dc074b830df44458e7ea5a28'
 )
 
 pkgver() {
-  cd $pkgname
+  cd $_pkgname
   git describe --tags | sed -r 's/\.([a-z])/\1/;s/([a-z])\./\1/;s/[^-]*-g/r&/;s/-/+/g'
 }
 
 prepare() {
-  cd "$srcdir/$pkgname"
+  cd "$srcdir/$_pkgname"
   patch -p1 < "$srcdir/mr1441.patch"
 }
 
@@ -73,7 +110,7 @@ build() {
     -D docs=true
     -D egl_device=true
     -D installed_tests=false
-    -D libdisplay_info=true
+    -D libdisplay_info=enabled
     -D wayland_eglstream=true
     -D tests=false
   )
@@ -81,7 +118,7 @@ build() {
   CFLAGS="${CFLAGS/-O2/-O3} -fno-semantic-interposition"
   LDFLAGS+=" -Wl,-Bsymbolic-functions"
 
-  arch-meson "$pkgname" build "${meson_options[@]}"
+  arch-meson "$_pkgname" build "${meson_options[@]}"
   meson compile -C build
 }
 
@@ -93,9 +130,14 @@ _check() (
   export NO_AT_BRIDGE=1 GTK_A11Y=none
   export MUTTER_DEBUG_DUMMY_MODE_SPECS="800x600@10.0"
 
+  # Tests fail:
+  # mutter:cogl+cogl/conform / cogl-test-offscreen-texture-formats-gles2
+  # mutter:core+mutter/stacking / fullscreen-maximize
+  ## https://gitlab.gnome.org/GNOME/mutter/-/issues/3343
   xvfb-run -s '-nolisten local +iglx -noreset' \
     mutter/src/tests/meta-dbus-runner.py --launch=pipewire --launch=wireplumber \
-    meson test -C build --print-errorlogs -t 5 --setup plain
+    meson test -C build --no-suite 'mutter/kvm' --no-rebuild \
+    --print-errorlogs --timeout-multiplier 10 --setup plain ||:
 )
 
 _pick() {
@@ -108,20 +150,10 @@ _pick() {
   done
 }
 
-package_mutter-dynamic-buffering() {
-  conflicts=(mutter)
-  provides=(mutter libmutter-13.so)
+package() {
+  provides=(libmutter-14.so)
 
   meson install -C build --destdir "$pkgdir"
 
   _pick docs "$pkgdir"/usr/share/mutter-*/doc
 }
-
-package_mutter-docs() {
-  pkgdesc+=" (documentation)"
-  depends=()
-
-  mv docs/* "$pkgdir"
-}
-
-# vim:set sw=2 sts=-1 et:
